logging:
  level:
    root: info
    com.example.springclouddemo: trace

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:spring_cloud_demo;USER=spring;MODE=MYSQL;DB_CLOSE_ON_EXIT=TRUE;IGNORECASE=FALSE
      username: spring
      password:
  sql:
    init:
      schema-locations: classpath:schema/spring-cloud-demo.sql
      username: spring
      password:

  cloud:
    discovery:
      enabled: false
    consul:
#      discovery:
#        enabled: false
#        register: false
#        register-health-check: false
      service-registry:
        auto-registration:
          enabled: false
management:
  health:
    consul:
      enabled: false
